// Mocks generated by Mockito 5.0.13 from annotations
// in search_calculate/test/home/data/repositories/companies_repository_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:search_calculate/home/data/datasources/companies_fixture_datasource.dart'
    as _i2;
import 'package:search_calculate/home/domain/entities/company.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [CompaniesFixtureDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompaniesFixtureDatasource extends _i1.Mock
    implements _i2.CompaniesFixtureDatasource {
  MockCompaniesFixtureDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> get templateData =>
      (super.noSuchMethod(Invocation.getter(#templateData),
          returnValue: <Map<String, dynamic>>[]) as List<Map<String, dynamic>>);
  @override
  List<_i3.Company> getCompanies() =>
      (super.noSuchMethod(Invocation.method(#getCompanies, []),
          returnValue: <_i3.Company>[]) as List<_i3.Company>);
  @override
  String toString() => super.toString();
}
