// Mocks generated by Mockito 5.0.13 from annotations
// in search_calculate/test/calculation_flow/presentation/cubit/calculation_flow_cubit_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:search_calculate/calculation_flow/domain/usecases/validate_form_data.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ValidateFormData].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateFormData extends _i1.Mock implements _i2.ValidateFormData {
  MockValidateFormData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool call(List<dynamic>? params) => (super
          .noSuchMethod(Invocation.method(#call, [params]), returnValue: false)
      as bool);
  @override
  String toString() => super.toString();
}
