// Mocks generated by Mockito 5.0.13 from annotations
// in search_calculate/test/home/domain/usecases/get_companies_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:search_calculate/home/domain/entities/company.dart' as _i4;
import 'package:search_calculate/home/domain/repositories/companies_repository.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [CompaniesRepositoryContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompaniesRepositoryContract extends _i1.Mock
    implements _i2.CompaniesRepositoryContract {
  MockCompaniesRepositoryContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Company>> getCompanies() =>
      (super.noSuchMethod(Invocation.method(#getCompanies, []),
              returnValue: Future<List<_i4.Company>>.value(<_i4.Company>[]))
          as _i3.Future<List<_i4.Company>>);
  @override
  String toString() => super.toString();
}
