// Mocks generated by Mockito 5.0.13 from annotations
// in search_calculate/test/home/presentation/cubit/home_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:search_calculate/home/domain/entities/company.dart' as _i5;
import 'package:search_calculate/home/domain/repositories/companies_repository.dart'
    as _i2;
import 'package:search_calculate/home/domain/usecases/get_companies.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeCompaniesRepositoryContract extends _i1.Fake
    implements _i2.CompaniesRepositoryContract {}

/// A class which mocks [GetCompanies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCompanies extends _i1.Mock implements _i3.GetCompanies {
  MockGetCompanies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CompaniesRepositoryContract get companiesRepository =>
      (super.noSuchMethod(Invocation.getter(#companiesRepository),
              returnValue: _FakeCompaniesRepositoryContract())
          as _i2.CompaniesRepositoryContract);
  @override
  _i4.Future<List<_i5.Company>> call() =>
      (super.noSuchMethod(Invocation.method(#call, []),
              returnValue: Future<List<_i5.Company>>.value(<_i5.Company>[]))
          as _i4.Future<List<_i5.Company>>);
  @override
  String toString() => super.toString();
}
