// Mocks generated by Mockito 5.0.13 from annotations
// in search_calculate/test/watchlist/data/repositories/watchlist_repository_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:search_calculate/watchlist/data/datasources/watchlist_local_datasource.dart'
    as _i3;
import 'package:search_calculate/watchlist/data/models/watchlist_item_model.dart'
    as _i4;
import 'package:search_calculate/watchlist/domain/entities/watchlist_item.dart'
    as _i5;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeSharedPreferences extends _i1.Fake implements _i2.SharedPreferences {
}

/// A class which mocks [WatchlistLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistLocalDatasource extends _i1.Mock
    implements _i3.WatchlistLocalDatasource {
  MockWatchlistLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(Invocation.getter(#sharedPreferences),
          returnValue: _FakeSharedPreferences()) as _i2.SharedPreferences);
  @override
  List<_i4.WatchlistItemModel> getWatchlist() => (super.noSuchMethod(
      Invocation.method(#getWatchlist, []),
      returnValue: <_i4.WatchlistItemModel>[]) as List<_i4.WatchlistItemModel>);
  @override
  dynamic removeFromWatchlist(_i5.WatchlistItem? newItem) =>
      super.noSuchMethod(Invocation.method(#removeFromWatchlist, [newItem]));
  @override
  dynamic addToWatchlist(_i5.WatchlistItem? newItem) =>
      super.noSuchMethod(Invocation.method(#addToWatchlist, [newItem]));
  @override
  String toString() => super.toString();
}
